# Generated by Django 4.1.7 on 2023-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMP', '0003_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.TextField(),
        ),
    ]
