# Generated by Django 4.1.7 on 2023-05-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMP', '0004_alter_company_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
